name: ModernFactions
main: com.modernfactions.ModernFactions
version: 0.0.1
api-version: 1.15
commands:
  testrandomteleport:
    description: Test the random teleport functionality
    default: op
  modernfactions:
    description: Modern Factions commands
    default: true;
    aliases: [f, mf, factions]