name: ModernFactions
main: com.modernfactions.ModernFactions
version: 0.0.1
api-version: 1.15
softdepend: [Vault]
commands:
  testrandomteleport:
    description: Test the random teleport functionality
    permission: modernfactions.testrandomteleport
  modernfactions:
    description: Modern Factions commands
    aliases: [f, mf, factions]
  refer:
    description: Refer a player
    aliases: [referral]
  territory:
    description: A visual view of the claim around you
    aliases: [terr, claims]
  modernfactionsadmin:
    description: Modern Factions admin command
    aliases: [mfadmin, mfa, fa, fadmin]
  discord:
    description: Get the Discord link
    aliases: [slack, chatroom]
  store:
    description: Get the store link
    aliases: [buycraft, donate, donation]
permissions:
  moderfactions.testrandomteleport:
    description: Access to the /testrandomteleport command
    default: op
  moderfactions.vip:
    description: Whether a player should have a vip prefix
    default: false
  moderfactions.admin:
    description: Modern Factions admin command
    default: op